### ISSUE TITLE
progressionbar not working

### ISSUE THREAD

**Issue by Skillmon** [equeim/unplayer#10]
Though I don't know how to call it in English this bar indicating the progression through a song isn't working for me on Sailfish 2.0 and the latest warehouse version. It's always full and shows the time the song is playing but not the overall duration of a song. It wasn't working on mp3 nor m4a files.

**Comment by equeim** [comment]
MP3 and M4A files works for me. It seems that in your case Tracker didn't scan track duration. Please write output of

```
tracker-info /path/to/file
```

**Comment by Skillmon** [comment]
Querying information for entity:'/media/sdcard/706A-FE88/Music/Rock/KoRn/Issues/korn - issues - 16 - dirty.mp3'
  'urn:uuid:b36e016b-047d-5ada-d4e5-274a156cf362'
Results:
  'http://purl.org/dc/elements/1.1/date' = '2012-11-18T15:14:12Z'
  'http://purl.org/dc/elements/1.1/date' = '2015-09-14T00:00:00Z'
  'http://purl.org/dc/elements/1.1/source' = 'urn:nepomuk:datasource:b9fb98a7193ea886d0dbaec53110d805'
  'tracker:added' = '2015-10-12T17:24:02Z'
  'tracker:modified' = '8278'
  'rdf:type' = 'http://www.w3.org/2000/01/rdf-schema#Resource'
  'rdf:type' = 'http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject'
  'rdf:type' = 'http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement'
  'rdf:type' = 'http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject'
  'rdf:type' = 'http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Media'
  'rdf:type' = 'http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Audio'
  'rdf:type' = 'http://www.tracker-project.org/temp/nmm#MusicPiece'
  'nie:byteSize' = '5432268'
  'nie:dataSource' = 'urn:nepomuk:datasource:b9fb98a7193ea886d0dbaec53110d805'
  'nie:isPartOf' = 'urn:uuid:6db763ce-786f-7081-853c-97efc3854d9e'
  'nie:url' = 'file:///media/sdcard/706A-FE88/Music/Rock/KoRn/Issues/korn%20-%20issues%20-%2016%20-%20dirty.mp3'
  'nfo:belongsToContainer' = 'urn:uuid:6db763ce-786f-7081-853c-97efc3854d9e'
  'tracker:available' = 'true'
  'maemo:relevance' = '1000000.0'
  'nie:isStoredAs' = 'urn:uuid:b36e016b-047d-5ada-d4e5-274a156cf362'
  'nie:mimeType' = 'audio/mpeg'
  'nfo:fileLastAccessed' = '2015-09-14T00:00:00Z'
  'nfo:fileLastModified' = '2012-11-18T15:14:12Z'
  'nfo:fileName' = 'korn - issues - 16 - dirty.mp3'
  'nfo:fileSize' = '5432268'

**Comment by Skillmon** [comment]
thats the output. sorry for not formatting as code. Funny thing is, that it works for some but for most files it doesnt

**Comment by equeim** [comment]
Reset Tracker database:

```
tracker-control --hard-reset
```

Wait for several minutes while Tracker is scanning filesystem, then try again.
