### ISSUE TITLE
Stop working in sailfishos 2.01

### ISSUE THREAD

**Issue by TMavica** [equeim/unplayer#11]
as title

**Comment by eson57** [comment]
Same for me! The app starts fine but I can't play.

**Comment by equeim** [comment]
Could you post terminal output, please? It works for me.

**Comment by eson57** [comment]
What's the command?

**Comment by ghost** [comment]
harbour-unplayer

**Comment by eson57** [comment]
Last login: Tue Jan 19 15:18:50 2016
,---
| SailfishOS 2.0.1.7 (Taalojärvi) (armv7hl)
'---
[nemo@Jolla ~]$ harbour-unplayer
[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL
[W] QQmlImportDatabase::registerPluginTypes:1875 - Module 'QtSparql' does not contain a module identifier directive - it cannot be protected from external registrations.
[W] QQmlImportDatabase::registerPluginTypes:1875 - Module 'QtSparql' does not contain a module identifier directive - it cannot be protected from external registrations.
[W] QQmlImportDatabase::registerPluginTypes:1875 - Module 'QtSparql' does not contain a module identifier directive - it cannot be protected from external registrations.

(harbour-unplayer:29807): Tracker-WARNING *_: Locale '0' is not set, defaulting to C locale
[D] DeclarativeCoverActionList::appendActions:143 - static void DeclarativeCoverActionList::appendActions(QQmlListProperty<DeclarativeCoverAction>_, DeclarativeCoverAction_)  QUrl( "" )
[D] DeclarativeCoverActionList::appendActions:143 - static void DeclarativeCoverActionList::appendActions(QQmlListProperty<DeclarativeCoverAction>_, DeclarativeCoverAction*)  QUrl( "image://theme/icon-cover-next-song" )
[D] DeclarativeCoverActionList::enableActiveCovers:341 - void DeclarativeCoverActionList::enableActiveCovers() "enableActiveCovers, process: /usr/bin/harbour-unplayer, winId: 0, action count: 2, enabled: 1"
[D] DeclarativeCoverActionList::disableActiveCovers:370 - void DeclarativeCoverActionList::disableActiveCovers() "disableActiveCovers, process: /usr/bin/harbour-unplayer, winId: 0, action count: 2, enabled: 0"
[D] DeclarativeCoverActionList::enableActiveCovers:341 - void DeclarativeCoverActionList::enableActiveCovers() "enableActiveCovers, process: /usr/bin/harbour-unplayer, winId: 0, action count: 2, enabled: 0"
| SailfishOS 2.0.1.7 (Taalojärvi) (armv7hl)
'---
[nemo@Jolla ~]$ harbour-unplayer
[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL
[W] QQmlImportDatabase::registerPluginTypes:1875 - Module 'QtSparql' does not contain a module identifier directive - it cannot be protected from external registrations.
[W] QQmlImportDatabase::registerPluginTypes:1875 - Module 'QtSparql' does not contain a module identifier directive - it cannot be protected from external registrations.
[W] QQmlImportDatabase::registerPluginTypes:1875 - Module 'QtSparql' does not contain a module identifier directive - it cannot be protected from external registrations.

(harbour-unplayer:29807): Tracker-WARNING *_: Locale '0' is not set, defaulting to C locale
[D] DeclarativeCoverActionList::appendActions:143 - static void DeclarativeCoverActionList::appendActions(QQmlListProperty<DeclarativeCoverAction>_, DeclarativeCoverAction_)  QUrl( "" )
[D] DeclarativeCoverActionList::appendActions:143 - static void DeclarativeCoverActionList::appendActions(QQmlListProperty<DeclarativeCoverAction>_, DeclarativeCoverAction*)  QUrl( "image://theme/icon-cover-next-song" )
[D] DeclarativeCoverActionList::enableActiveCovers:341 - void DeclarativeCoverActionList::enableActiveCovers() "enableActiveCovers, process: /usr/bin/harbour-unplayer, winId: 0, action count: 2, enabled: 1"
[D] DeclarativeCoverActionList::disableActiveCovers:370 - void DeclarativeCoverActionList::disableActiveCovers() "disableActiveCovers, process: /usr/bin/harbour-unplayer, winId: 0, action count: 2, enabled: 0"
[D] DeclarativeCoverActionList::enableActiveCovers:341 - void DeclarativeCoverActionList::enableActiveCovers() "enableActiveCovers, process: /usr/bin/harbour-unplayer, winId: 0, action count: 2, enabled: 0"

**Comment by napcode** [comment]
I do see the same issue. It seems to be an MP3 problem with unplayer. Vorbis works fine.
Here is a log snippet:
`
image://theme/icon-cover-next-song
1" 
** Message: don't know how to handle audio/mpeg, mpegversion=(int)1, mpegaudioversion=(int)1, layer=(int)3, rate=(int)44100, channels=(int)2, parsed=(boolean)true
[D] DeclarativeCoverActionList::enableActiveCovers:341 - void DeclarativeCoverActionList::enableActiveCovers() "enableActiveCovers, process: /usr/bin/harbour-unplayer, winId: 1, action count: 2, enabled: 1" 
[D] DeclarativeCoverActionList::setWindowProperty:270 - void DeclarativeCoverActionList::setWindowProperty(QStringList, bool)  
[D] DeclarativeCoverActionList::setWindowProperty:280 - void DeclarativeCoverActionList::setWindowProperty(QStringList, bool) "CoverActionList::setWindowProperty: com.jolla.coveraction.pid31923.id1
trigger
0
image://theme/icon-cover-play
com.jolla.coveraction.pid31923.id1
trigger
1
`

**Comment by Kabouik** [comment]
Would you have any idea what is causing this issue @equeim?

This is by far the best player I've used on Sailfish (and yet I have a paid version of QuasarMX): minimalistic, simple, and complete (tags and directories). It's a shame that it does not work anymore.

**Comment by napcode** [comment]
Unplayer uses gstreamer to playback media files. The error message `** Message: don't know how to handle audio/mpeg, mpegversion=(int)1, mpegaudioversion=(int)1, layer=(int)3, rate=(int)44100, channels=(int)2, parsed=(boolean)true` is actually from gstreamer. 

After playing aroudn a bit, it looks like the gstreamer deployment on SFOS 2.0 is unable to playback MP3 content. I couldn't get it to work on the commandline either (try `gst-launch-0.10 filesrc location=filename.xyz ! decodebin ! pulsesink`).  Non-MP3 files work fine.

**Comment by ghost** [comment]
GStreamer on Sailfish 2.0 is now 1.0 instead of 0.10. Maybe they removed the 0.10 stuff in the latest update or something, I didn't check.

**Comment by napcode** [comment]
Installing the missing package from openrepos.net fixes this. It's obviously not the best solution but in the meantime...

**Comment by Kabouik** [comment]
What missing package are you referring to exactly @napcode? Any solution, even if not the best, would already be a huge improvement!

**Comment by napcode** [comment]
I left this out intentionally as it's easy to break something.  Anyway, [here you go](https://openrepos.net/content/ikozzz/gst-fluendo-mp3).

**Comment by eson57** [comment]
@napcode Thanks, that really worked. Is there anything special you think it might break?

**Comment by sebma** [comment]
@TMavica Can you please change the title of your issue to something a little bit more precise ? It will help us to avoid creating duplicates. Thanks

**Comment by monstersintokyo** [comment]
Sadly installing gst-fluendo-mp3 did not fix the issue for me on version 2.0.2.43.

`** Message: don't know how to handle application/x-id3` is still shown. 

Moreover tried the command from #8 - did not help either.

**Comment by equeim** [comment]
Sorry for the long delay. GStreamer 0.10 in not supported in SailfishOS 2.0.x so I switched to 1.0. MP3 and AAC should work now, please test it.

**Comment by eson57** [comment]
Works fine again, thank you! I really missed this player.  :+1:

**Comment by monstersintokyo** [comment]
Thank you!
