### ISSUE TITLE
Artist icons shows covers of deleted albums

### ISSUE THREAD

**Issue by Tichy** [equeim/unplayer#12]
Sometimes, the artists icons shows the covers of deleted albums. I don't know if it's a tracker problem, but it looks like it doesn't happen with the default media player.

If I delete the corresponding files in ~/.cache/media-art the deleted album's cover don't appear anymore in the artist icon.

To reproduce, try to import many albums of the same artist, then delete all of them except one.

**Comment by Tichy** [comment]
I have to correct myself. It happened to me once also with the default media player.

**Comment by equeim** [comment]
Should be fixed in 1.0.0 (which will be released soon).
