### ISSUE TITLE
Add support for the Opus codec in OGG container (audio/x-opus+ogg)

### ISSUE THREAD

**Issue by sebma** [equeim/unplayer#15]
Hi, I see that the Speex codec is supported.

But OGG/Speex has been abondonned 7 years in favor of the Opus codec which can be embedd in OGG or WebM containers.

If you are not convinced that Opus is a great codec, please consider [this](https://en.wikipedia.org/wiki/File:Opus_quality_comparison_colorblind_compatible.svg), [this](https://en.wikipedia.org/wiki/File:Opus_bitrate%2Blatency_comparison.svg) and [this](https://en.wikipedia.org/wiki/Opus_%28audio_format%29) :)

Can you add the support for the OGG/Opus codec ?

**Comment by equeim** [comment]
Please test it on the latest version.

**Comment by sebma** [comment]
It works :+1:
