### ISSUE TITLE
I can't create new playlist

### ISSUE THREAD

**Issue by carmenfdezb** [equeim/unplayer#17]
When I create a new playlist (I typed playlist name and clicked on accept), any list isn't added.

**Comment by mase76** [comment]
The same issue here.

**Comment by equeim** [comment]
@mase76 Do you have this issue in 1.4.0 (I've just released it)? It fixed the case when Unplayer couldn't save playlists if ~/Music/playlists directory was missing.

**Comment by mase76** [comment]
Yes, I got the update in the same moment. However not the whole queue is added to the playlist, just the current playing title.
BTW: What can I do with selected titles? There is no action, that makes sense to me.
