### ISSUE TITLE
Feature request : Open files with Unplayer from Sailfish File Browser

### ISSUE THREAD

**Issue by sebma** [equeim/unplayer#18]
Hi,

If I type this command for Unplayer to be the default application to open "application/ogg" files : 
`$ xdg-mime default harbour-unplayer.desktop application/ogg`

and try to open a ogg file from `harbour-file-browser`, it launches `harbour-unplayer` but as if I did not give any argument to `harbour-unplayer`

You can see below that the argument in the Exec command line for `harbour-unplayer` is missing : 
```
$ grep Exec= /usr/share/applications/harbour-unplayer.desktop
Exec=harbour-unplayer
```
Can you please fix this ?

**Comment by equeim** [comment]
Unplayer doesn't support opening files using command line arguments. The only way to play a file is to select in inside the app. Though I may add this feature in future.

**Comment by equeim** [comment]
The next version (1.0.0) will support this feature. However you will need to set Unplayer as default for each MIME type that you want to open with it, either by using xdg-mime command or directly editing ~/.local/share/applications/mimeapps.list file.
