### ISSUE TITLE
Multiple tags are read/displayed as one

### ISSUE THREAD

**Issue by ghost** [equeim/unplayer#20]
If a single music file has the following tags:
artist:"First"
artist:"Second"
genre:"Genre1"
genre:"Genre2"

It will be displayed as being a song from artist "First Second", and the genre will be "Genre1 Genre2". These tags should be separated so the song can be found under artist "First" and under artist "Second". Same thing for genre tags, and probably other tags as well (but these are the most used/most needed ones). When displaying song details, the artists and genres should be listed as "First, Second" and "Genre1, Genre2".

**Comment by equeim** [comment]
Could send me an example of such file?

**Comment by d9h02f** [comment]
I've sent an email.
