### ISSUE TITLE
Feature request: sort songs by date

### ISSUE THREAD

**Issue by DylanVanAssche** [equeim/unplayer#21]
Is it possible to add an option to create a playlist with songs sorted by date added? When you have a large music collection and you add some new songs it's difficult to find those quickly.

**Comment by equeim** [comment]
Added in https://github.com/equeim/unplayer/commit/8c50a95950297694107cf0ed890d790623ebb259.

**Comment by DylanVanAssche** [comment]
Oh thank you!
