### ISSUE TITLE
cover art inside

### ISSUE THREAD

**Issue by ghost** [equeim/unplayer#22]
hello equeim 
thanks for your beautiful app.

i am using the last release of unplayer, i can not see cover art embedded in  my tracks. all my music have cover art inside of track.FLAC

**Comment by equeim** [comment]
FLAC should be supported. Try to reset the library. If this won't work, send me an example of file.

**Comment by ghost** [comment]
yes:  fixed reseting the library thanks. i will send to you a pull request here to complete the spanish translate soon. please add paypal in openrepos and in the app.  EQUEIM > # 1 .

**Comment by equeim** [comment]
Translations are also managed on Weblate, link in the README (but pull request would be also ok).
