### ISSUE TITLE
Lots of album art not shown.

### ISSUE THREAD

**Issue by eson57** [equeim/unplayer#24]
Only few embedded covers are now shown, and they where all visible when using Jolla tracker.
There's also a "problem" with not respecting the .nomedia file. Now I have not only the music in my Unplayer, but also my books and other audio files. 
Please let me know if I can help trace the cover issue.

**Comment by equeim** [comment]
Does resetting library solves the problem?
.nomedia files are indeed ignored, I will add it in the next version.

**Comment by eson57** [comment]
No, reset does not help.

**Comment by equeim** [comment]
Could you send an example of file, which cover does not show?

**Comment by eson57** [comment]
Of course! Here's one (had to zip it). Looks perfectly normal in Banshee, puddletag, VLC... you name it.
[Take_Me_To_The_River.zip](https://github.com/equeim/unplayer/files/919697/Take_Me_To_The_River.zip)

**Comment by eson57** [comment]
Thanks! 👍
