### ISSUE TITLE
FeaturesRequest: random covers arts

### ISSUE THREAD

**Issue by ghost** [equeim/unplayer#26]
HELLO equeim 
- Currently in the section of genres does not appear any cover incorporated in the tracks of the albums, then I would say that all the covers art that exist in each genre box appear moving the covers arts one after another like animation.
![20170415105351](https://cloud.githubusercontent.com/assets/24536606/25064556/76ddc32c-21ca-11e7-8839-80d28363c02f.jpg)

- Same here 

![unplayer](https://cloud.githubusercontent.com/assets/24536606/25064603/8693c4be-21cb-11e7-9fc2-d92e8164f65a.jpg)

**Comment by ghost** [comment]
Hello equeim
any plan to implement my request?
basically it is that the albums are changing one after another creating type animation, in the section of album or artist section.

**Comment by equeim** [comment]
Creating animated cover image is not trivial thing to do, and it is certainly won't be in the 1.4.0 (I also plan to release it very soon). I'm not even sure that it is actually needed. On the other hand, just setting a random cover like with other categories, is very easy. Don't know why I didn't do it before.

**Comment by ghost** [comment]
Yes. it not a request really needed,but  i just wanted to look better visually.
Also i had other request by adding 3 funtions in coverAction like: Previous - Play -  Following
Actually only there are 2 funtions in coverAction.  :  )

**Comment by ghost** [comment]
wow my requests is on the way...!
donation for it, is on the way too  :  )
t h a n k s.

**Comment by ghost** [comment]
as i promised: 66V11938K6783712J

**Comment by equeim** [comment]
Thanks!

**Comment by ghost** [comment]
hello equeim
3 buttons in lock screen is missing.
also my feature request; random  media art is missing or i do not know where was implemented
spanish translation need some fix, i will send one PR now
thanks

**Comment by equeim** [comment]
Random media cover for genres is in 1.4.0 and works for me, are you sure that you are running latest version? Also try to reset library.

**Comment by ghost** [comment]
i am on 1.4.0, but i do not see my wish. i am confused now.
i reseted the library too, but same.

**Comment by ghost** [comment]
let is see version 1.4.1 if working.

**Comment by equeim** [comment]
You mean that "Genres" item on library pages and list items in genres list display generic "note" icon? Does "Artists", "Albums", "Tracks" items display random media art correctly? If it's the case, did resetting the library change anything? If resetting didn't work, then I don't know what is it, because random cover for genres is implemented exactly the same as random cover for artists, etc.

**Comment by ghost** [comment]
i have sony xperia x sf 2.2.1.18 unplayer 1.4.1 still same issue, i do not see cover art changing in any place even in library place.
so take  your time on this issue because something is happening i am not sure if you understand me as well my wish. but no worries i am happy with the last 2 releases 1.4.0 1.4.1.
so i will reopen this issue to check more time.
thank you for you work.

**Comment by ghost** [comment]
note: i have only  .flac (1000 tracks) files  with cover art embedded.
so i did some test from few minutes ago, then i could say that random cover art is working i guess manually. i am not sure if this feature was implemented to work like manually or automatically.
Anyway random cover art manually also looks great : )

**Comment by equeim** [comment]
What do you mean by "manually"?

**Comment by ghost** [comment]
i say Manually is when it changes the cover art only when i do click into library and any option there. 
example: when i open unplayer first time, it only show one cover art in the library option. so if i need library option show another cover art, then i need close unplayer and reopen then will show diferent cover art in library option as example.

**Comment by equeim** [comment]
Well yeah, currently random cover art is loaded only when element that displays it is created. I.e. for "Library" item on main screen it is only when app is opened, for "Artists", "Albums", etc it reloads every time when library screen is opened. It doesn't automatically reloads on timer (or when going back from previous screen. Not sure which option is better), it was this way from the beginning. I may add this feature in the future, but is is not a priority.

**Comment by ghost** [comment]
well, i liked cover art automatically  because it moving constantly, the music is action, so people when dancing music they are moving or wish are moving, the light in the party is better if are in constant moving. so i wished something equal in unplayer.
