### ISSUE TITLE
Use Weblate for translations

### ISSUE THREAD

**Issue by ghost** [equeim/unplayer#3]
https://hosted.weblate.org/

It's free (as in beer) because Unplayer is published under a free (as in freedom) license, and it makes it really easy for people to help translate the project.

**Comment by lewadedun** [comment]
or https://www.transifex.com/ )))

**Comment by equeim** [comment]
https://hosted.weblate.org/projects/unplayer/translations/

**Comment by eson57** [comment]
So what happened to Swedish translation at weblate? It' not there any more.

**Comment by equeim** [comment]
I know. I wrote to Hosted Weblate admin about this issue, he hasn't answered yet.

**Comment by eson57** [comment]
Ok, thanks.

**Comment by carmenfdezb** [comment]
Spanish translation is done ;)
