### ISSUE TITLE
make shuffle truly random

### ISSUE THREAD

**Issue by benaryorg** [equeim/unplayer#31]
As described in [this excellent stackoverflow thread](https://stackoverflow.com/questions/24256258/order-by-random-with-seed-in-sqlite), SQLite's `ORDER BY RANDOM()` (which is used by shuffle if I'm not mistaken) does not contain true randomness and therefore returns the same list everytime you start up the player/the DB connection is opened.

That bothers me because I therefore listen to the same set of songs in the same order every time I use shuffle, which kind of isn't the point of shuffle.

**Comment by benaryorg** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=54836649)](https://www.bountysource.com/issues/54836649-make-shuffle-truly-random?utm_source=54836649&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by aadiaz1804** [comment]
I'll give it a shot tomorrow to look for an alternative method of randomizing.

**Comment by ghost** [comment]
Still open?

**Comment by benaryorg** [comment]
@DeStoken I assume so.

**Comment by ronyfadel** [comment]
created PR @ https://github.com/equeim/unplayer/pull/32
