### ISSUE TITLE
Feature Request: support albums with multiple discs

### ISSUE THREAD

**Issue by FabriceColin** [equeim/unplayer#37]
Tracks from albums with multiple discs are currently jumbled together, i.e. all songs on track 1, then all songs on track 2 etc...
It would help if tracks listing took discs in consideration and sorted tracks by disc number then track number.

**Comment by equeim** [comment]
Hmm, I can't find disc number in specifications of file formats metadatas. If it is contained only in album title, I won't be able to add this feature.

**Comment by FabriceColin** [comment]
I don't believe it's in the album title as Unplayer doesn't show any digit in the album title of the tracks I have copied over from iTunes.
What specifications are you looking at? Maybe I can help.
Googling for "mp3 metadata disc number" shows some promising leads.

**Comment by equeim** [comment]
Send me a file that contains info about disc number.

**Comment by FabriceColin** [comment]
How can I send you example files?
In the meantime, I have run id3info (from http://id3lib.sourceforge.net/) on some and saw that the disc information is stored as either a TPOS or a TPA tag, e.g. "TPOS 1/1", "TPA 1/2" or "TPA 2/2", and not in the song name or title (TIT2 or TT2).
Rhythmbox on my Linux machine is able to extract and make sense of those tags.

**Comment by equeim** [comment]
Send it over email.
