### ISSUE TITLE
Feature Request: Play and stop

### ISSUE THREAD

**Issue by goroboro** [equeim/unplayer#44]
It would be handy if there was an option to set the Play option to a 'Play and Stop'. This is particularly useful if you just want to play a single track and then stop immediately after it has played. I'm requesting this because this would make it possible to use this application for playing backing tracks etc if you are a performing artist. See for example, the features that are highlighted for backing track applications like https://play.google.com/store/apps/details?id=com.syntax.apps.backingtrackstudio

**Comment by goroboro** [comment]
5 EUR Paypal donation sent, in the hopes that you might look at this feature :D
Confirmation number: 6WY477495N3548902.
Also, hopefully this encourages other folks to donate for ongoing development.

**Comment by equeim** [comment]
Sorry for the late answer.
One thing is not clear to me: what should app do when user presses play button again? Should it play the next track or current one from the beginning?

**Comment by goroboro** [comment]
Hey. Thanks for getting back to me. I appreciate your work on this application.
I guess it doesn't particularly matter, however if the track reaches its end and stops, then presumably the next track would make sense. However, if the track is manually stopped (i.e. the user interrupts the track), then starting the same track again would make sense in that case.
The key point here is that if you select a track from a directory listing or playlist, there should be an option to only play that track and not to automatically start playing the next one when that track completes. However you choose to implement this, would be fine, since the user can then select an alternate track from the playlist.
The use case is: A musician is using the application to play backing tracks. During a performance, the musician may wish to play a song but not necessarily go immediately to the next song. (i.e. The musician may want to talk or introduce the next song before proceeding; or the musician may want time to change the order of the songs in the performance or remove a track from the playlist based on the audience reaction). The stop after playing the track gives the musician time to do this and then select the next track manually and play that.

**Comment by goroboro** [comment]
Woot! Thanks for adding this. You rock.
