### ISSUE TITLE
featureRequest: inverted ambiences

### ISSUE THREAD

**Issue by carlosgonz0** [equeim/unplayer#47]
currently is not supporting inverted ambiences, will cool enabling :  )

**Comment by equeim** [comment]
What do you mean? I've just tested it on my Jolla, and it works.
![20181218005849](https://user-images.githubusercontent.com/5106414/50118259-39b83400-0260-11e9-949a-9b5af94bb1fa.jpg)

**Comment by carlosgonz0** [comment]
yes thanks, my mistake.
