### ISSUE TITLE
Cover art from ID3v2 tag not used when APE tag is also used

### ISSUE THREAD

**Issue by a-dekker** [equeim/unplayer#48]
I was missing some cover art but could not explain why. The reason was it also had an APE tag. Could you also check ID3v2 for cover art in those cases? I saw you made a fix to get cover art from APE, maybe that caused an ignore of ID3v2 cover art?

Great app by the way!

**Comment by equeim** [comment]
Yeah, I didn't consider the case when file can have both APE and ID3v2 tags. Could send me an example of such file?

**Comment by a-dekker** [comment]
It should be easy to reproduce, add a ID3v2 tag with cover art and an APE tag without cover art with your favorite mp3 tag editor.

Here is a dummy mp3 which should represent that:
[1-second-of-silence.zip](https://github.com/equeim/unplayer/files/2798869/1-second-of-silence.zip)

**Comment by a-dekker** [comment]
thanks, hope to test it in a new release!
