### ISSUE TITLE
Build section missing in README.md

### ISSUE THREAD

**Issue by fvacek** [equeim/unplayer#49]
Hi, I'm still looking for good music player for SailfisOS and unplayer looks very promising to me, but I'm not able to build it in SDK. I like to fix some bugs or make contribution. I'm not experienced SailfishOS developer but I have some knowledge of Qt and QML, so some build hints can help me a lot. I'm author of https://github.com/fvacek/notagplayer, but unfortunately BB10 doesn't exist any more.

**Comment by bionade24** [comment]
Source: https://sailfishos.org/wiki/Tutorial_-_Building_packages_manually
