### ISSUE TITLE
FeatureRequest: a HD  Icon to HD audio files is playing....

### ISSUE THREAD

**Issue by carlosgonz0** [equeim/unplayer#65]
I would like to see a tiny icon with HD or DIGITAL  symbology in to describe a high definition audio file is being played like Flac 16bit/24bit

![Captura_20191205_004](https://user-images.githubusercontent.com/45316884/70261527-9dcd5400-1760-11ea-9d4c-ecd052dcd481.png)

**Comment by carlosgonz0** [comment]
Hi @equeim, It is possible to push it foward this request?

**Comment by equeim** [comment]
I can add bit depth and sample rate information to the file properties page, but I don't really see the value in displaying a special icon for that.

**Comment by carlosgonz0** [comment]
Most SailfishOS devices  has 24bits output by 3.5mm jacks, but also Jolla is considering implementing the LDAC features in sailfish, ldac is a free protocol from sony that enables high definition streaming via bluetooth.
For these reasons I would like Unplayer to be able to display the depth of a track of each audio track  being played on the main playback page.
An icon with letters or symbols is more nice  intuitive for the main Unplayer playback page to show bit-depth.

**Comment by carlosgonz0** [comment]
My idea is that the Icons being showed in each track with 16bits  up no matter what format it is.
Another idea without an icon is to display 16bit or 24bit somewhere on the playback page, as shown in the screenshot above.

**Comment by carlosgonz0** [comment]
Prototypes  
![Captura_20200418_001_edit](https://user-images.githubusercontent.com/45316884/79639094-dd796300-8178-11ea-943b-5f299466363f.png)
![Captura_20200418_003_edit](https://user-images.githubusercontent.com/45316884/79639096-deaa9000-8178-11ea-8d61-952e0b653b64.png)

**Comment by carlosgonz0** [comment]
HR icon on when playing tracks in HD.
![d95cff9e10659e8dba9f6a0aeff9661f](https://user-images.githubusercontent.com/45316884/82618939-73eadb00-9ba2-11ea-901d-c6d47598d41c.jpeg)

**Comment by carlosgonz0** [comment]
Hi dev
I want  to know if there is plans to push this feature, if not ,  I close it.

**Comment by GNUuser** [comment]
Hi @equeim 
How is going?

**Comment by equeim** [comment]
I've got an implementation almost ready. What do you think?
![Снимок_Экрана_20200930_001](https://user-images.githubusercontent.com/5106414/94615702-dec6c400-02b0-11eb-80b4-fa452eff6e7b.png)

**Comment by carlosgonz0** [comment]
It looks very good!, It  apply to all the tracks or only is showed with tracks 12bit-24bit?

**Comment by equeim** [comment]
Well, current plan is to show it for all local files with option to hide.

**Comment by carlosgonz0** [comment]
Yeah option to hide is good, thank you. I donate you for this feature too.

**Comment by carlosgonz0** [comment]
My donation is on the way for this feature. Thank you.   I HAVE PAYPAL ISSUES, check the paypal link please.

**Comment by carlosgonz0** [comment]
https://blog.verdanditeam.com/audiophile-ways-on-sailfishos
:  )

**Comment by carlosgonz0** [comment]
Thank you: 3KW87592C87781***
