### ISSUE TITLE
Earphone/Headset control support

### ISSUE THREAD

**Issue by eson57** [equeim/unplayer#7]
I have a pair of [Jaybird BlueBuds X](http://www.amazon.com/JayBird-BlueBuds-Sport-Bluetooth-Headphones/dp/B00AIRUOI8), which is a great headset for music listening, and it works perfectly well with Jolla default music player. 
Would be very nice if the headset controls also was supported in my favourite player.  :)

**Comment by equeim** [comment]
Already fixed, new version will be released when translations will be updated.

**Comment by eson57** [comment]
Thanks a lot, and yea... Swedish translation done! Even if weblate is a real pain for translators.  ;)
