### ISSUE TITLE
Updated translations for Norwegian, Dutch, French, German and Spanish are missing

### ISSUE THREAD

**Issue by ghost** [equeim/unplayer#9]
Probably has something to do with having edited the English 'translation'. Could you take a look?

Also, it would be great if you could somehow 'reuse' identical strings (like 'add to playlist') so they don't need to be translated multiple times.

**Comment by equeim** [comment]
Thanks, it seems that translation changed hasn't been commited automatically. Will be fixed soon.

Maybe I will switch to id-based translations. However when I tried to use it last time it refused to load fallback English strings (it works in Jolla apps, so I guess that I missed something).
